[project]
name = 'Decentralized-Carbon-Footprint-Tracking'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.emissions-reporting]
path = 'contracts/emissions-reporting.clar'
clarity_version = 2
epoch = 2.5

[contracts.entity-registration]
path = 'contracts/entity-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.methodology-verification]
path = 'contracts/methodology-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.reduction-certification]
path = 'contracts/reduction-certification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
